== Introduction

This is a repository that is designed to make it easy to set up and maintain
other C++-centric projects, by centralizing code (mostly CMake code) that
runs CI.

Unlike some other projects of this nature, it is not designed for use as a
template repository. Rather, a few lines of CMake code will set up a dependency
on this repository that can then be easily kept up to date.

This repository provides functionality in three areas:

- Github workflows
- CMake utility functions
- CMake toolchains

=== Getting started

First, https://github.com/cpm-cmake/CPM.cmake#adding-cpm[add `get_cpm.cmake`] to
your project's repository. Then, make your CMakeLists.txt file look something
like this at the top:

[source,cmake]
----
cmake_minimum_required(VERSION 3.27)

project(my_project)

include(cmake/get_cpm.cmake)
cpmaddpackage("gh:intel/cicd-repo-infrastructure#abc123")
----

=== Auto updates

If you rely on this repository at a branch name rather than a specific tag or
hash, then what you probably intended was to pin to the head of that branch. In
that case, the first thing this repository does is check that it is actually at
the head of the upstream branch, and if not, update. This behaviour is
controlled with the `INFRA_SELF_UPDATE` CMake option, which is `ON` by default.

For example, if your CMakeLists.txt says:
[source,cmake]
----
cpmaddpackage("gh:intel/cicd-repo-infrastructure#dev")
----

When you run CMake the first time, this repository is downloaded (at the head of
the `dev` branch) and stored in the CPM cache.

The second time you run CMake, this repository is already in the cache. This is
fine if you are pinning to an immutable hash, but if you are using a branch as
above, the upstream branch may have moved on. This is the case where an
auto-update check is performed, to keep the downloaded repository at the head of
`dev`.

Auto-updates will not occur in the following circumstances:

- `INFRA_SELF_UPDATE` is `OFF`
- This repository is not fetched with CPM
- You're using a filesystem copy rather than from a remote repository
