
== Linting and formatting

This repository provides support for linting and formatting code and ensuring
that it stays that way.

=== `clang-format`

If the `INFRA_PROVIDE_CLANG_FORMAT` option is `ON`, a
https://github.com/intel/cicd-repo-infrastructure/blob/main/.clang-format[`.clang-format`]
file will be provided.

To use `clang-format` from CMake, we depend on
https://github.com/TheLartians/Format.cmake[Format.cmake]. This results in three
CMake targets for clang-format:

- `clang-format`
- `check-clang-format`
- `fix-clang-format`

Of these, the `clang-format` target is actually the least used. It runs
`clang-format` on each file in the repository, with the results going to `stdout`.
This is not typically very useful.

The `check-clang-format` target is used by CI builds: it exits with an error if
any file requires formatting, i.e. if any file differs after `clang-format`
runs.

The `fix-clang-format` target is the most useful for developers: it uses
`clang-format` to format files in-place.

NOTE: `fix-clang-format` won't change files that are already changed in git's
working tree. Robotic formatting changes should be applied in a separate commit
for easy review.

NOTE: For preference, we'll find the `clang-format` that exists alongside the
compiler being used.

=== `cmake-format`

If the `INFRA_PROVIDE_CMAKE_FORMAT` option is `ON`, a
https://github.com/intel/cicd-repo-infrastructure/blob/main/.cmake-format.yaml[`.cmake-format.yaml`]
file will be provided.

As with clang-format, https://github.com/TheLartians/Format.cmake[Format.cmake]
provides three targets for cmake-format:

- `cmake-format`
- `check-cmake-format`
- `fix-cmake-format`

=== `black`

Python code is formatted using https://github.com/psf/black[black]. There are
two targets with the appropriate behavior:

- `check-black-format`
- `fix-black-format`

NOTE: Like `fix-clang-format`, `fix-black-format` won't change files that are
already changed in git's working tree.

=== `clang-tidy`

If the `INFRA_PROVIDE_CLANG_TIDY` option is `ON`, a
https://github.com/intel/cicd-repo-infrastructure/blob/main/.clang-tidy[`.clang-tidy`]
file will be provided.

CMake has built-in support: to use `clang-tidy` with a cmake target, set the
`CXX_CLANG_TIDY` property on it.

However, if you have a header-only library, this repository provides a
`clang_tidy_interface` function that makes it easy to lint header files.

[source,cmake]
----
clang_tidy_interface(my_target)
----

This finds all the headers in the given target, and for each one, it creates an
empty `.cpp` file that does nothing but `#include` that header. It creates a
separate library target just for that generated `.cpp` file, and sets the
`CXX_CLANG_TIDY` property on that library target.

Each such generated target is then rolled up into a single `clang-tidy` target.

The upshot of this is that each header is linted correctly. It also has the side
effect of checking that each header can be included on its own.

The way that `clang_tidy_interface` works depends on the target properties. If
https://cmake.org/cmake/help/latest/command/target_sources.html[`target_sources`]
is used with
https://cmake.org/cmake/help/latest/command/target_sources.html#file-sets[`FILE_SET`],
`clang_tidy_interface` finds the headers using that method. Otherwise -- when
https://cmake.org/cmake/help/latest/command/target_include_directories.html[`target_include_directories`]
is used -- `clang_tidy_interface` globs the headers in the include directories.

NOTE: If `target_include_directories` is used to specify a target's headers,
adding a header file won't clang-tidy it until CMake is re-run.

You can still take advantage of `clang_tidy_interface` even if not all your code
is linting cleanly, by providing exclusions:

[source,cmake]
----
clang_tidy_interface(
  TARGET my_target
  EXCLUDE_DIRS mylib/A mylib/B
  EXCLUDE_FILES mylib/file.hpp
  EXCLUDE_FILESETS exclusions)
----

In particular the `EXCLUDE_FILESETS` argument can be used together with
`target_sources`, separating excluded headers into a separate `FILE_SET`.

NOTE: `clang-tidy` is only a useful target when building with a clang toolchain.
If you are not building with clang, the `clang-tidy` target will do nothing.

NOTE: As with `clang-format`, for preference, we'll find the `clang-tidy` that
exists alongside the compiler being used.

=== Enabled clang-tidy checks

The following https://clang.llvm.org/extra/clang-tidy/checks/list.html[`clang-tidy` check] categories are enabled:

* bugprone-*
* clang-diagnostic-*
* clang-analyzer-*
* cppcoreguidelines-*
* misc-*
* modernize-*
* performance-*
* portability-*
* readability-*

In addition, the following specific checks are enabled:

* https://clang.llvm.org/extra/clang-tidy/checks/boost/use-to-string.html[boost-use-to-string]
* https://clang.llvm.org/extra/clang-tidy/checks/google/build-explicit-make-pair.html[google-build-explicit-make-pair]
* https://clang.llvm.org/extra/clang-tidy/checks/google/build-namespaces.html[google-build-namespaces]
* https://clang.llvm.org/extra/clang-tidy/checks/google/default-arguments.html[google-default-arguments]
* https://clang.llvm.org/extra/clang-tidy/checks/google/explicit-constructor.html[google-explicit-constructor]
* https://clang.llvm.org/extra/clang-tidy/checks/google/readability-casting.html[google-readability-casting]
* https://clang.llvm.org/extra/clang-tidy/checks/google/runtime-int.html[google-runtime-int]
* https://clang.llvm.org/extra/clang-tidy/checks/hicpp/signed-bitwise.html[hicpp-signed-bitwise]

The following specific checks are _disabled_ because they are aliases for other
checks, and clang-tidy does not deduplicate them:

* https://clang.llvm.org/extra/clang-tidy/checks/bugprone/narrowing-conversions.html[bugprone-narrowing-conversions]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/narrowing-conversions.html[cpp-coreguidelines-narrowing-conversions]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-c-arrays.html[cppcoreguidelines-avoid-c-arrays]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/modernize/avoid-c-arrays.html[modernize-avoid-c-arrays]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-magic-numbers.html[cppcoreguidelines-avoid-magic-numbers]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/readability/magic-numbers.html[readability-magic-numbers]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/c-copy-assignment-signature.html[cppcoreguidelines-c-copy-assignment-signature]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/misc/unconventional-assign-operator.html[misc-unconventional-assignment-operator]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/explicit-virtual-functions.html[cppcoreguidelines-explicit-virtual-functions]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-override.html[modernize-use-override]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/macro-to-enum.html[cppcoreguidelines-macro-to-enum]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/modernize/macro-to-enum.html[modernize-macro-to-enum]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/noexcept-destructor.html[cppcoreguidelines-noexcept-destructor]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/performance/noexcept-destructor.html[performance-noexcept-destructor]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/noexcept-move-operations.html[cppcoreguidelines-noexcept-move-operations]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/performance/noexcept-move-constructor.html[performance-noexcept-move-constructor]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/noexcept-swap.html[cppcoreguidelines-noexcept-swap]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/performance/noexcept-swap.html[performance-noexcept-swap]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/non-private-member-variables-in-classes.html[cppcoreguidelines-non-private-member-variables-in-classes]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/misc/non-private-member-variables-in-classes.html[misc-non-private-member-variables-in-classes]
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/use-default-member-init.html[cppcoreguidelines-use-default-member-init]
  aliases
  https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-default-member-init.html[modernize-use-default-member-init]

The following checks are disabled for specific reasons:

* https://clang.llvm.org/extra/clang-tidy/checks/bugprone/easily-swappable-parameters.html[bugprone-easily-swappable-parameters] -
  may be enabled someday, but currently too onerous.
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-non-const-global-variables.html[cppcoreguidelines-avoid-non-const-global-variables] -
  the nature of embedded work makes this check ill-conceived.
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/missing-std-forward.html[cppcoreguidelines-missing-std-forward] -
  this check misdiagnoses some common things.
* https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/pro-bounds-pointer-arithmetic.html[cppcoreguidelines-pro-bounds-pointer-arithmetic] -
  may be enabled someday, but currently too onerous.
* https://clang.llvm.org/extra/clang-tidy/checks/misc/include-cleaner.html[misc-include-cleaner] -
  warns on omnibus headers.
* https://clang.llvm.org/extra/clang-tidy/checks/misc/non-private-member-variables-in-classes.html[misc-non-private-member-variables-in-classes] -
  public variables don't contribute to class invariants.
* https://clang.llvm.org/extra/clang-tidy/checks/modernize/concat-nested-namespaces.html[modernize-concat-nested-namespaces] -
  it's a style choice.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-length.html[readability-identifier-length] -
  generic code uses lots of short identifiers.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html[readability-identifier-naming] -
  one of the most expensive checks; not worth the cost.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/magic-numbers.html[readability-magic-numbers] -
  the nature of embedded work makes this too onerous.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/named-parameter.html[readability-named-parameter] -
  it's a style choice.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/qualified-auto.html[readability-qualified-auto] -
  it's a style choice.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/redundant-inline-specifier.html[readability-redundant-inline-specifier] -
  `inline` is mostly, but not _only_ for the linker.
* https://clang.llvm.org/extra/clang-tidy/checks/readability/uppercase-literal-suffix.html[readability-uppercase-literal-suffix] -
  it's a style choice.

It is likely in the future that more clang-tidy checks will be enabled.

=== `mypy`

Python linting is available using https://mypy-lang.org/[`mypy`]. To lint python
files, call `mypy_lint`:

[source,cmake]
----
mypy_lint(FILES file1.py file2.py)
----

And then building the `mypy-lint` target runs `mypy` against these files.

=== The `quality` target

The `quality` target encompasses other targets:

- `check-clang-format`
- `check-cmake-format`
- `clang-tidy`
- `check-black-format`
- `mypy-lint`

This is a convenient target to build on the command-line to check that
CI will pass. And any formatting failures can be fixed up by building the
`fix-clang-format`, `fix-cmake-format`, and `fix-black-format` targets.

NOTE: The `quality` job that is run by CI always uses the latest clang version
enabled in CI. Sometimes this can disagree with what is run locally, if you have
reason to be building locally with an older supported toolchain. For example, if
you build locally with clang-15, but CI runs clang-18, you are likely to get
minor differences of formatting or linting that cause CI failures. Use the
latest tools for best quality!

=== The `ci-quality` and `*-branch-diff` targets

Because linters can be somewhat expensive to run on a whole codebase,
alternative targets for CI lint only what changed in a pull request.

When the environment variable `PR_TARGET_BRANCH` is set to `main` (or any other
branch that a PR will be merged into), `clang-tidy-branch-diff` builds the
clang-tidy targets for the files which have changed between the PR branch and
the target branch. Likewise `mypy-lint-branch-diff` does the same thing for the
mypy-lint targets. The `ci-quality` target depends on these "diff" targets
rather than on the corresponding "full" targets.

It is fairly easy to set up CI to do this, but note that both branches must be
fetched. See the `quality_checks_pass` job in
https://github.com/intel/cicd-repo-infrastructure/blob/main/ci/.github/workflows/unit_tests.yml[`.github/workflows/unit_tests.yml`]
for an example.
