
== Testing

This repository provides CMake functions to make defining tests easy.

=== Defining unit tests

[source,cmake]
----
add_unit_test(
  my_test
  CATCH2
  FILES my_test.cpp
  LIBRARIES my_lib)
----

`add_unit_test` is a basic function for defining unit tests. Four unit test
framework options are supported (according to the given argument):

- https://github.com/catchorg/catch2[`CATCH2`]
- https://github.com/google/googletest[`GTEST`]
- https://github.com/cpp-testing/gunit[`GUNIT`]
- https://github.com/snitch-org/snitch[`SNITCH`]

https://github.com/emil-e/rapidcheck[RapidCheck] is also provided for
property-based testing; it integrates with either Catch2 or GoogleTest (or
GUnit, which is based on GoogleTest). See the RapidCheck documentation for how
to use it with either of those frameworks.

The arguments to `add_unit_test` are:

- test name
- optionally, a test framework to use
- `FILES` to be compiled
- optionally, extra `INCLUDE_DIRECTORIES` to use
- optionally, extra `LIBRARIES` to link with
- optionally, extra `SYSTEM_LIBRARIES` to link with
- optionally, `NORANDOM`

NOTE: By default, tests will run in a random order unless the `NORANDOM`
argument is given.

It is possible to define a unit test without using any of the supported
frameworks. In that case, just write your own test program, with `main`
returning zero on test success and non-zero on test failure.

=== Python unit tests

[source,cmake]
----
add_unit_test(
  my_test
  PYTEST
  FILES my_test.py
  LIBRARIES my_lib)
----

`add_unit_test` also supports running tests using https://pytest.org[pytest]. In
this case the include paths implied by `LIBRARIES` are passed to the test with
the command line `--include_dirs <paths>`. And the command line options can be
handled with pytest's
https://docs.pytest.org/en/8.0.x/reference/reference.html#pytest.hookspec.pytest_addoption[`addoption`
hook].

=== Fuzz tests

[source,cmake]
----
add_fuzz_test(
  my_test
  FILES my_test.cpp
  LIBRARIES my_lib)
----

`add_fuzz_test` is a basic function for defining tests that use Google's
https://github.com/google/fuzztest[`fuzztest`]. `GTEST` and `rapidcheck` macros
are also available with these tests.

NOTE: Fuzz tests are enabled only when the compiler is Clang.

`add_fuzz_test` takes the same optional arguments as `add_unit_test`.

=== BDD feature tests

GUnit also provides for BDD-style "feature tests", which define tests in a
https://cucumber.io/docs/gherkin/[Cucumber/Gherkin syntax] feature file, and
define steps in the C++.

[source,cmake]
----
add_feature_test(
    my_feature_test
    FILES
    my_steps.cpp
    FEATURE
    my_test.feature
    LIBRARIES
    my_lib
    warnings)
----

`add_feature_test` takes the same optional arguments as `add_unit_test`.

=== Compilation failure tests

When writing compile-time code, it's often useful to check compilation failures
to test that for example library users get a clear help message. To do that, use
`add_compile_fail_test`:

[source,cmake]
----
add_compile_fail_test(my_fail_test.cpp LIBRARIES my_lib)
----

Compilation failure tests consist of a single source file and are unrelated to
testing frameworks. The source file can define what is expected as a message
with a comment:

[source,cpp]
----
// EXPECT: FLAGRANT SYSTEM ERROR
----

If no `EXPECT` comment is found, by default we will expect a `static_assert` to
fire.

NOTE: Compilation failure tests are not part of the `all` target, for obvious
reasons. But they are set up as tests that are designed to fail; they can be run
with the `test` target or by `ctest`.

NOTE: Because `ctest` information is updated at CMake time, changing the
`EXPECT` comment of a test requires re-running CMake to update what is expected.

`add_compile_fail_test` takes the same optional arguments as `add_unit_test`.

=== Sanitizers

The `sanitizers` library works similarly to the `warnings` library, but provides
compiler command-line options that enable various sanitizers.

Which sanitizers are turned on is specified at CMake time by the environment
variable `SANITIZERS`.

[source,bash]
----
$ SANITIZERS=undefined cmake --preset=clang
----

When a sanitizer is set like this, any targets created with `add_unit_test` or
`add_feature_test` will use the sanitizer flags. The
xref:github.adoc#_unit_tests_workflow[unit_tests workflow] runs tests with
(separately) the
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html[undefined behavior],
https://clang.llvm.org/docs/AddressSanitizer.html[address] and
https://clang.llvm.org/docs/ThreadSanitizer.html[thread] sanitizers.

=== Valgrind

CMake has built-in support for https://valgrind.org/[valgrind]; using `ctest`
with the `-T memcheck` option runs unit tests with valgrind. This is also done
by the xref:github.adoc#_unit_tests_workflow[unit_tests workflow].

=== Test code coverage

To get code coverage reports, use the `COVERAGE` argument with `add_unit_test`.
[source,cmake]
----
add_unit_test(
  my_test
  CATCH2
  COVERAGE
  FILES my_test.cpp
  LIBRARIES my_lib)
----

This will generate a target that will produce a test coverage report in `<build directory>/coverage`.

[source,bash]
----
$ cmake --build build -t coverage_report_my_test
# coverage report is in build/coverage/my_test.coverage_report.txt
----

If multiple tests generate coverage reports, the rolled-up report can be built
using the `cpp_coverage_report` target:
[source,bash]
----
$ cmake --build build -t cpp_coverage_report
# combined coverage report is in build/coverage_report.txt
----

The `COVERAGE` argument can also be used with `add_feature_test` or `add_fuzz_test`.

NOTE: Test coverage uses LLVM's
https://clang.llvm.org/docs/SourceBasedCodeCoverage.html[source-based code
coverage] tooling, so is only available when using a clang toolchain, and only
for C++ (not Python) tests.
